#!/bin/bash

# Path where the script is installed
FULL_TEST_PATH="/usr/libexec/redtest/redtest-helloworld-api/"
FULL_LOGS_PATH="/var/log/redtest/redtest-helloworld-api/"

# Start the helloworld service
systemctl start redtesthelloapi.service

# Export environment variable in order to ask python to not buffer the lines
export PYTHONUNBUFFERED=1

# First create the logs directory
mkdir -p $FULL_LOGS_PATH

# Remove the previous log file if it exists
rm -f "$FULL_LOGS_PATH/*.tap"

# Run the tests and save the results in a log file
pytest-3 --tap-stream "${FULL_TEST_PATH}" | tee "$FULL_LOGS_PATH/tests_helloworld.tap"

# Stop the helloworld service
systemctl stop redtesthelloapi.service

# End of the test
exit 0